import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { Fragment } from "react";

export const metadata = {
	title: "Homepage | Bakso Dono Reborn",
	description: "Generated by create next app",
};

export default function HomeRoot({ children }) {
	return (
		<Fragment>
			<Navbar />
			{children}
			<Footer />
		</Fragment>
	);
}
