import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata = {
	title: "Homepage | Bakso Dono Reborn",
	description: "Generated by create next app",
};

export default function HomeRoot({ children }) {
	return (
		<>
			<Navbar />
			{children}
			<Footer />
		</>
	);
}
