import { Toaster } from "sonner";
import "./globals.css";

export const metadata = {
	title: "Homepage | Bakso Dono Reborn",
	description: "Generated by homepage | Bakso Dono Reborn",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Toaster position="top-center" />
				{children}
			</body>
		</html>
	);
}

