import { CartProvider } from "@/hooks/CartContext";

export const metadata = {
	title: "Order | Bakso Dono Reborn",
	description: "Generated by create next app",
};

export default function OrderRoot({ children }) {
	return <CartProvider>{children}</CartProvider>;
}
