export const metadata = {
	title: "Order | Bakso Dono Reborn",
	description: "Generated by create next app",
};

export default function OrderRoot({ children }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
